--- 
abstract: Lightweight currency conversion using WebserviceX.NET
author: Christopher H. Laco
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Finance-Currency-Convert-WebserviceX
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTTP::Response: 0
  LWP: 0
  perl: 5.6.1
tests: t/*.t t/*/*.t
version: 0.06000
